version: "3.3"

services:
  mcl:
    image: kagurazakanyaa/mcl:latest
    network_mode: host
    tty: true
    stdin_open: true
    volumes:
      - "./plugins:/app/plugins"
      - "./config:/app/config"
      - "./data:/app/data"
      - "./bots:/app/bots"
    restart: unless-stopped
