version: "3.3"

services:
  mcl:
    build: .
    image: kagurazakanyaa/mcl:latest
    network_mode: host
    volumes:
      - "./plugins:/app/plugins"
      - "./config:/app/config"
      - "./data:/app/data"
    restart: unless-stopped
